# Generated by Django 3.1.3 on 2020-11-17 18:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Citizen',
            fields=[
                ('id', models.PositiveIntegerField(primary_key=True, serialize=False)),
                ('firstName', models.CharField(max_length=32)),
                ('lastName', models.CharField(max_length=32)),
                ('password', models.CharField(max_length=64)),
                ('role', models.PositiveSmallIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cityName', models.CharField(max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='Crime',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('crimeName', models.CharField(max_length=64)),
                ('description', models.TextField(max_length=255)),
                ('severity', models.PositiveSmallIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reportTime', models.DateTimeField()),
                ('priority', models.SmallIntegerField()),
                ('remarks', models.TextField(max_length=255)),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reportsite.city')),
                ('crimeName', models.ManyToManyField(to='reportsite.Crime')),
                ('patriot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='reportsite.citizen')),
                ('traitor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='reportsite.citizen')),
            ],
        ),
        migrations.CreateModel(
            name='InvestigationQueue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('priority', models.SmallIntegerField()),
                ('agentID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reportsite.citizen')),
                ('reportID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reportsite.report')),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('commentTime', models.DateTimeField()),
                ('priority', models.SmallIntegerField()),
                ('content', models.TextField(max_length=255)),
                ('informant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reportsite.citizen')),
                ('reportID', models.ManyToManyField(to='reportsite.Report')),
            ],
        ),
        migrations.AddField(
            model_name='citizen',
            name='city',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reportsite.city'),
        ),
    ]
