# Generated by Django 3.1.3 on 2020-12-03 17:02

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('reportsite', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='commentTime',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.RemoveField(
            model_name='comment',
            name='reportID',
        ),
        migrations.AddField(
            model_name='comment',
            name='reportID',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='reportsite.report'),
        ),
        migrations.AlterField(
            model_name='report',
            name='reportTime',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
